networks:
  busroot:
    name: pet-tracker-network
    driver: bridge

services:
  app-server:
    image: app-server:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/pet_tracker
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: pHrJvh4ICt2Fh7Qu
      JWT_SECRET: cGV0LXRyYWNrZXItbWFuYWdlbWVudC1zZWN1cmUta2V5LXByb2Q=
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_DB: pet_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pHrJvh4ICt2Fh7Qu
    ports:
      - "5431:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: