ALTER TABLE owner ADD created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE owner ADD updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE pet ADD created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE pet ADD updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;