spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/pet_tracker
    username: postgres
    password: pHrJvh4ICt2Fh7Qu

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

jwt:
  secret: cGV0LXRyYWNrZXItbWFuYWdlbWVudC1zZWN1cmUta2V5LWRldg==
  expired-time: 3600000