spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/pet_tracker
    username: postgres
    password: pHrJvh4ICt2Fh7Qu
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    baselineOnMigrate: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

jwt:
  secret: cGV0LXRyYWNrZXItbWFuYWdlbWVudC1zZWN1cmUta2V5LWRldg==
  expired-time: 604800000