spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pet_tracker
    username: postgres
    password: pHrJvh4ICt2Fh7Qu
    driver-class-name: org.postgresql.Driver

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true