spring:
  application:
    name: tracker

  datasource:
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    baselineOnMigrate: true

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

jwt:
  expired-time: 3600000